### ISSUE TITLE
Getting error during dataset upload

### ISSUE THREAD

**Issue by yvaclav** [gooddata/gooddata-java#620] opened 2018-06-19 07:00 UTC
```
This can be known limitation, see https://github.com/gooddata/gooddata-java/wiki/Known-limitations
at com.gooddata.gdc.DataStoreService.upload(DataStoreService.java:111)
at com.gooddata.gdc.DataStoreService.upload(DataStoreService.java:100)
at com.gooddata.dataset.DatasetService.loadDatasets(DatasetService.java:157)
```

This is during upload of one of multiple CSV files. Happens quite uncommonly/unpredictably. The affected file in this case was empty - just headers - so it was very small.

Using SDK version 2.25.1

**Comment by jimirocks** [comment] 2018-06-20 07:04
Hello, thanks for report, however could you add more info:
1. Make sure there is some other request before using DataStoreService (i.e. fetch your project)
2. Pls send us the whole stacktrace, especially the part where the `requestId` is logged

**Comment by jimirocks** [comment] 2018-06-20 07:07
Additionally the original "limitation" the message is refering to was claimed to be fixed on the gooddata backend since Novemeber 2017, but well this could be a regression.

**Comment by yvaclav** [comment] 2018-06-20 07:18
We will fetch the project before upload as a workaround even when the issue page claims this is fixed. Not sure how that works when we upload multiple files at once though. Whether the first several datasets may go through and some upload in the middle can fail.

Here is the full stack trace. However cannot find a requestId in it.

```
com.ytica.analytics.tooling.commons.exceptions.DataUploadException: Failed to upload data to workspace (x0y4sc50cu04po2iwo2fpncvbeo9f3q3)
at com.ytica.analytics.tooling.writer.upload.UploadToYtica.uploadDatasets(UploadToYtica.java:97)
at com.ytica.analytics.tooling.writer.upload.UploadToYtica.upload(UploadToYtica.java:63)
at com.ytica.analytics.tooling.writer.YticaWriter.writeData(YticaWriter.java:270)
at com.ytica.analytics.tooling.writer.YticaWriter.writeData(YticaWriter.java:174)
at com.ytica.analytics.tooling.server.Application$MessageServlet.doPost(Application.java:87)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:205)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
at org.eclipse.jetty.server.Server.handle(Server.java:531)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:760)
at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:678)
at java.lang.Thread.run(Thread.java:748)
Caused by: com.gooddata.dataset.DatasetException: Load datasets [achievements, activities, agents, assessments, coins, conversations, customers, products] failed: Unable to load
at com.gooddata.dataset.DatasetService.loadDatasets(DatasetService.java:168)
at com.ytica.analytics.tooling.writer.upload.UploadToYtica.uploadDatasets(UploadToYtica.java:91)
... 26 more
Caused by: com.gooddata.gdc.DataStoreException: Got 500 while uploading to https://analytics.ytica.com:443/gdc/uploads/x0y4sc50cu04po2iwo2fpncvbeo9f3q3_oVi/tmp/1529359258276-0/dataset.products.csv.This can be known limitation, see https://github.com/gooddata/gooddata-java/wiki/Known-limitations
at com.gooddata.gdc.DataStoreService.upload(DataStoreService.java:111)
at com.gooddata.gdc.DataStoreService.upload(DataStoreService.java:100)
at com.gooddata.dataset.DatasetService.loadDatasets(DatasetService.java:157)
... 27 more
Caused by: com.github.sardine.impl.SardineException: Unexpected response (500 Internal Server Error)
at com.github.sardine.impl.handler.ValidatingResponseHandler.validateResponse(ValidatingResponseHandler.java:48)
at com.github.sardine.impl.handler.VoidResponseHandler.handleResponse(VoidResponseHandler.java:34)
at com.github.sardine.impl.handler.VoidResponseHandler.handleResponse(VoidResponseHandler.java:29)
at com.gooddata.http.client.GoodDataHttpClient.execute(GoodDataHttpClient.java:317)
at com.gooddata.gdc.DataStoreService$FakeCloseableHttpClient.execute(DataStoreService.java:253)
at com.github.sardine.impl.SardineImpl.execute(SardineImpl.java:823)
at com.gooddata.gdc.GdcSardine.execute(GdcSardine.java:33)
at com.github.sardine.impl.SardineImpl.put(SardineImpl.java:755)
at com.github.sardine.impl.SardineImpl.put(SardineImpl.java:738)
at com.github.sardine.impl.SardineImpl.put(SardineImpl.java:726)
at com.github.sardine.impl.SardineImpl.put(SardineImpl.java:696)
at com.github.sardine.impl.SardineImpl.put(SardineImpl.java:689)
at com.github.sardine.impl.SardineImpl.put(SardineImpl.java:682)
at com.github.sardine.impl.SardineImpl.put(SardineImpl.java:676)
at com.gooddata.gdc.DataStoreService.upload(DataStoreService.java:105)
... 29 more
```

**Comment by yvaclav** [comment] 2018-06-20 08:15
We can try. However keep in mind this is relatively rare and we are able easily recover from this state so it is quite a low priority for us. It may take a while to respond then.

**Comment by jimirocks** [comment] 2018-06-26 07:34
Identified as known issue on the backend (appearing rarely), so closing it here, @yvaclav in case  you will have significant trouble cause of this, do not hesitate to contact support directly.

**Closed by jimirocks** 2018-06-26 07:34 UTC
Labels: need more info
